### ISSUE TITLE
Other combinations

### ISSUE THREAD

**Issue by kriskwiatkowski** [post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem#13]
As MLKEM is out (soon), the good question now is - do we want to include codepoints for more combinations than P256-MLKEM768?

I think P256-MLKEM768 should stay, but I don't have a clear opinion about use cases for other combinations.

**Comment by dconnolly** [comment]
Support for secp384+MLKEM...1024? I think? @tomato42

**Comment by tomato42** [comment]
secp384r1MLKEM1024 is in already:
https://github.com/post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem/blob/0eee72f28caf4a8c06bc9d661c7e39bf0271a424/draft-kwiatkowski-tls-ecdhe-mlkem.md?plain=1#L81

**Comment by kriskwiatkowski** [comment]
Yes, I think that is the only one we want to add. Should be done very soon.
Let's close that issue.
