### ISSUE TITLE
Public key validation

### ISSUE THREAD

**Issue by bwesterb** [post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem#19]
Perhaps good to spend a few words on what to do if the public key doesn't pass the new public key validation check. That'd be similar to sending a key share of the wrong size, and the appropriate thing to do would be to send a bad_parameter alert.

**Comment by kriskwiatkowski** [comment]
Good point! Will do

**Comment by kriskwiatkowski** [comment]
Draft now contains following text:

```
For both groups, the server MUST perform the encapsulation key check
described in Section 7.3 of {{FIPS203}} on the client's encapsulation
key, and abort with an illegal_parameter alert if it fails.
```
